# Site settings
title: Be Strong and be fun
description: "Cunji's log"
baseurl: ""
url: "https://younotafish.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name: Cunji Song
  url: https://younotafish.github.io
  email: cunjisong.fact@gmail.com

# Build settings
markdown: kramdown
include:
  - _pages

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink: /:year-:month-:day/:title
paginate: 5

# Excludes
exclude: [Gemfile, Gemfile.lock, tale.gemspec]

# Disqus (Set to your disqus id)
disqus: jekyll-tale
